config/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path

admin.site.site_title = "Willay"
admin.site.site_header = "Willay"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("willay.users.urls", namespace="auth")),
    path("", include("willay.claims.urls", namespace="claims")),
    path("", lambda req: redirect("claims:claim-map"), name="home"),
]

willay/claims/urls.py
from django.urls import path

from . import views


app_name = "claims"

urlpatterns = [
    path("map/", views.MapView.as_view(), name="claim-map"),
    path("map/data/", views.MapDataView.as_view(), name="claim-map-data"),
    path("claims/", views.ClaimListView.as_view(), name="claim-list"),
    path("claims/create/", views.ClaimCreateView.as_view(), name="claim-create"),
    path("claims/<int:id>/", views.ClaimDetailView.as_view(), name="claim-detail"),
    path("claims/export/", views.ClaimExportView.as_view(), name="claim-export"),
]

willay/users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path


app_name = "users"

urlpatterns = [
    path("logout", auth_views.LogoutView.as_view(), name="logout"),
]

willay/claims/models.py
from django.conf import settings
from django.contrib.gis.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from model_utils.models import TimeStampedModel


class Category(TimeStampedModel):

    name = models.CharField(_("Name"), max_length=50)
    marker_icon = models.ImageField(
        _("Marker icon"),
        upload_to="claims/category/marker_icon/%Y/%m/%d/",
        null=True,
        blank=True,
        help_text=_("32x32 png image is required"),
    )

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")
        default_related_name = "categories"
        ordering = ("name",)

    def __str__(self):
        return self.name


class Claim(TimeStampedModel, models.Model):

    category = models.ForeignKey("Category", on_delete=models.CASCADE)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL,
    )

    address = models.CharField(_("Address"), max_length=200)
    point = models.PointField(_("Point"), null=True, blank=True)
    date = models.DateTimeField(_("Date"), default=timezone.now)
    description = models.TextField(_("Description"))
    photo = models.ImageField(
        _("Photo"), upload_to="claims/claim/photo/%Y/%m/%d/", null=True, blank=True,
    )
    verified = models.BooleanField(_("Verified"), default=False)

    class Meta:
        verbose_name = _("Claim")
        verbose_name_plural = _("Claims")
        default_related_name = "claims"
        ordering = ("-date",)

    def __str__(self):
        return f"{self.address} - {self.date}"

willay/users/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    class Meta:
        db_table = "auth_user"

willay/claims/forms.py
from django import forms
from django.utils.translation import ugettext as _

from .models import Category, Claim


class ClaimForm(forms.ModelForm):
    class Meta:
        model = Claim
        fields = (
            "category",
            "address",
            "point",
            "description",
            "photo",
        )
        widgets = {
            "point": forms.HiddenInput,
        }

    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request

    def save(self, *args, **kwargs):
        instance = super().save(*args, **kwargs)
        if self.request.user.is_authenticated:
            instance.user = self.request.user
            instance.save()
        return instance


class ExportClaimsForm(forms.Form):

    start_date = forms.DateField(label=_("Start date"))
    end_date = forms.DateField(label=_("End date"))
    category = forms.ModelChoiceField(queryset=Category.objects.all(), required=False,)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["start_date"].widget.attrs.update(
            {
                "data-provide": "datepicker",
                "date-date-format": "yyyy-mm-dd",
                "data-date-end-date": "0d",
            }
        )
        self.fields["end_date"].widget.attrs.update(
            {
                "data-provide": "datepicker",
                "date-date-format": "yyyy-mm-dd",
                "data-date-end-date": "0d",
            }
        )

    def clean(self):
        cleaned_data = super().clean()
        start_date = cleaned_data.get("start_date")
        end_date = cleaned_data.get("end_date")
        if start_date and end_date and end_date < start_date:
            self.add_error(
                "start_date", _("The start date must be lower that end date")
            )

willay/claims/views.py
import csv
from io import StringIO

from django.conf import settings
from django.contrib import messages
from django.core.serializers import serialize
from django.http import HttpResponse
from django.urls import reverse
from django.utils.translation import ugettext as _
from django.views.generic import CreateView, DetailView, FormView, TemplateView, View
from django_filters.views import FilterView

from . import filters, forms
from .models import Category, Claim


class ClaimCreateView(CreateView):

    template_name = "claims/claim_create.html"
    model = Claim
    form_class = forms.ClaimForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"request": self.request})
        return kwargs

    def get_success_url(self, **kwargs):
        messages.success(self.request, _("Claim created, thanks for report a claim"))
        return reverse("claims:claim-list")


class ClaimListView(FilterView):

    template_name = "claims/claim_list.html"
    model = Claim
    paginate_by = settings.PAGINATION_DEFAULT_PAGE_SIZE
    context_object_name = "claims"
    filterset_class = filters.ClaimFilter

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({"categories": Category.objects.all()})
        return context


class ClaimDetailView(DetailView):

    template_name = "claims/claim_detail.html"
    model = Claim
    context_object_name = "claim"
    pk_url_kwarg = "id"


class MapView(TemplateView):

    template_name = "claims/map.html"


class MapDataView(View):
    def get(self, request, *args, **kwargs):
        qs = Claim.objects.exclude(point=None)
        data = serialize(
            "claim-geojson",
            qs,
            geometry_field="point",
            fields=("address", "description", "date",),
        )
        return HttpResponse(data, content_type="application/json")


class ClaimExportView(FormView):

    template_name = "claims/export.html"
    form_class = forms.ExportClaimsForm

    def form_valid(self, form):
        data = form.cleaned_data
        fields = (
            "category__name",
            "address",
            "point",
            "date",
            "description",
            "verified",
        )

        stream = StringIO()
        writer = csv.writer(stream, delimiter=",")
        writer.writerow(fields)
        qs = Claim.objects.filter().select_related("category")
        if data["category"]:
            qs = qs.filter(category=data["category"])
        qs = qs.filter(date__gte=data["start_date"], date__lte=data["end_date"],)

        for record in qs.values_list(*fields):
            writer.writerow(record)
        stream.seek(0)
        start_formatted = data["start_date"].strftime("%Y-%m-%d")
        end_formatted = data["end_date"].strftime("%Y-%m-%d")
        filename = f"{start_formatted}_{end_formatted}.csv"
        response = HttpResponse(stream.getvalue(), content_type="text/csv")
        response["Content-Disposition"] = f"attachment; filename={filename}"
        return response

willay/templates/_filter.html
{% load i18n crispy_forms_tags %}
<style>
  .filter-form .form-group {
    margin-right: 10px;
    padding-bottom: 5px;
  }
  .filter-form .form-control {
    margin-left: 10px;
  }
  .filter-form button {
    margin-bottom: 5px;
  }
</style>
<div class="row">
  <div class="col-md-12">
    <form class="form-inline filter-form">
      {% crispy filter.form filter.helper %}
      <button class="btn btn-outline-secondary" type="submit">
        <i class="fas fa-search"></i>
        {% trans 'Filter' %}
      </button>
    </form>
  </div>
</div>
<br/>

willay/templates/_pagination.html
{% load pagination_tags i18n %}
{% if page_obj.paginator.num_pages > 1 %}
<nav class="text-center">
  <ul class="pagination">
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}&{{ request|querystring_without_page }}">
        <i class="fas fa-angle-left"></i>
      </a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#">
        <i class="fas fa-angle-left"></i>
      </a>
    </li>
    {% endif %}
    {% for page_number in page_obj|pagination_range:10 %}
    {% if page_number == page_obj.number %}
    <li class="page-item active disabled">
      <a class="page-link" href="#">{{ page_number }}</a>
    </li>
    {% elif page_number == '...' %}
    <li class="page-item disabled">
      <a class="page-link" href="#">{{ page_number }}</a>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_number }}&{{ request|querystring_without_page }}">
        <span>{{ page_number }}</span>
      </a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}&{{ request|querystring_without_page }}">
        <i class="fas fa-angle-right"></i>
      </a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#">
        <i class="fas fa-angle-right"></i>
      </a>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

willay/templates/base.html
{% load staticfiles i18n socialaccount %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'vendor/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/css/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/css/bootstrap-datepicker3.min.css' %}">
    {% block css %}{% endblock %}

    <title>Willay | {{ title }}</title>

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'home' %}">Willay</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'claims:claim-map' %}">{% trans 'Map' %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'claims:claim-list' %}">{% trans 'Claims' %}</a>
          </li>
        </ul>
        <ul class="navbar-nav float-lg-right">
          <li>
            <a class="nav-link" href="{% url 'claims:claim-export' %}">
              <i class="fas fa-table"></i> {% trans 'Export' %}
            </a>
          </li>
          <li>
            <a class="nav-link" href="https://github.com/erickgnavar/willay">
              <i class="fab fa-github"></i> {% trans 'Code' %}
            </a>
          </li>
          {% if not user.is_authenticated %}
          <li class="nav-item active">
            <a class="nav-link" href="{% provider_login_url "twitter" %}">
              <i class="fas fa-sign-in-alt"></i> {% trans 'Login' %}
            </a>
          </li>
          {% else %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{ user.username }}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'auth:logout' %}">
                <i class="fas fa-log-out-alt"></i> {% trans 'Logout' %}
              </a>
            </div>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container">
      <div class="row">
        <main role="main" class="col-md-12 ml-sm-auto col-lg-12 pt-3 px-4">
          {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          {% endfor %}
          {% block content %}{% endblock content %}
          <br/>
        </main>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'vendor/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'vendor/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendor/js/bootstrap-datepicker.min.js' %}"></script>

    {% block javascript %}{% endblock %}
  </body>
</html>

willay/templates/claims/claim_create.html
{% extends 'base.html' %}
{% load i18n static form_tags %}
{% block css %}
  <link href="{% static 'vendor/leaflet/leaflet.css' %}" rel="stylesheet"/>
  <style>
    #map {
      width: 100%;
      height: 400px;
    }
  </style>
{% endblock css %}
{% block content %}
  <div class="row">
    <div class="col-md-12">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
          <div class="col-md-6">
            {% field form.category %}
            {% field form.address %}
            {% field form.point %}
            <div id="map"></div>
          </div>
          <div class="col-md-6">
            {% field form.description %}
            {% field form.photo %}
          </div>
        </div>
        <br/>
        <button class="btn btn-outline-primary" type="submit">
          <i class="fas fa-save"></i>
          {% trans 'Save' %}
        </button>
        <a class="btn btn-outline-secondary" href="{% url 'claims:claim-list' %}">
          {% trans 'Cancel' %}
        </a>
      </form>
    </div>
  </div>
{% endblock content %}
{% block javascript %}
  <script src="{% static 'vendor/leaflet/leaflet.js' %}"></script>
  <script src="{% static 'js/claim-create-map.js' %}"></script>
{% endblock javascript %}

willay/templates/claims/claim_detail.html
{% extends 'base.html' %}
{% load i18n static %}
{% block css %}
  <link href="{% static 'vendor/leaflet/leaflet.css' %}" rel="stylesheet"/>
  <style>
    #map {
      width: 100%;
      height: 400px;
    }
  </style>
{% endblock css %}
{% block content %}
  <div class="row">
    <div class="col-md-9">
      <h3>{{ claim.category.name }}</h3>
      <p class="float-right">
        {% if claim.verified %}
          <span class="badge badge-primary">
            <i class="fas fa-check-circle"></i>
            {% trans 'Verified' %}
          </span>
        {% else %}
          <span class="badge badge-danger">
            {% trans 'No verified' %}
          </span>
        {% endif %}
      </p>
      <p>
        <b>{% trans 'Date' %}:</b> {{ claim.date }}
      </p>
      <p>
        <b>{% trans 'Address' %}:</b> {{ claim.address }}
      </p>
      {% if claim.user %}
        <p>
          {% trans 'By' %} <i>{{ claim.user.username }}</i>
        </p>
      {% endif %}
      {% if claim.point %}
      <div id="map"></div>
      {% endif %}
      <h5>
        {% trans 'Description' %}
      </h5>
      <p>
        {{ claim.description }}
      </p>
    </div>
    <div class="col-md-3">
      <a class="btn btn-sm btn-block btn-outline-success" href="{% url 'claims:claim-create' %}">
        <i class="fas fa-plus"></i>
        {% trans 'New claim' %}
      </a>
      <hr/>
    </div>
  </div>
{% endblock content %}
{% block javascript %}
  <script src="{% static 'vendor/leaflet/leaflet.js' %}"></script>
  <script src="{% static 'js/claim-detail-map.js' %}"></script>
  {% if claim.point %}
  <script>
    drawMap('map', {{ claim.point.y }}, {{ claim.point.x }});
  </script>
  {% endif %}
{% endblock javascript %}

willay/templates/claims/claim_list.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
  <div class="row">
    <div class="col-md-9">
      {% for claim in claims %}
      <div class="row">
        <div class="col-md-3">
          {% if claim.photo.name %}
          <img src="{{ claim.photo.url }}" alt="" width="100%" />
          {% else %}
          <!--TODO: put a default image-->
          {% endif %}
        </div>
        <div class="col-md-9">
          <h3 class="card-title">{{ claim.category.name }}</h3>
          <p>
            {{ claim.address }} <i class="float-right">{{ claim.date }}</i>
          </p>
          <p class="float-right">
            {% if claim.verified %}
              <span class="badge badge-primary">
                <i class="fas fa-check-circle"></i>
                {% trans 'Verified' %}
              </span>
            {% else %}
              <span class="badge badge-danger">
                {% trans 'No verified' %}
              </span>
            {% endif %}
          </p>
          {% if claim.user %}
          <p>
            {% trans 'By' %} <i>{{ claim.user.username }}</i>
          </p>
          {% endif %}
          <p>
            {{ claim.description }}
          </p>
          <a href="{% url 'claims:claim-detail' claim.id %}" class="btn btn-outline-primary">
            <i class="fas fa-plus"></i>
            {% trans 'More info' %}
          </a>
        </div>
      </div>
      <br/>
      {% endfor %}
    </div>
    <div class="col-md-3">
      <a class="btn btn-sm btn-block btn-outline-success" href="{% url 'claims:claim-create' %}">
        <i class="fas fa-plus"></i>
        {% trans 'New claim' %}
      </a>
      <hr/>
      <div class="list-group">
        <a href="?" class="list-group-item list-group-item-action {% if not request.GET.category %}active{% endif %}">
          {% trans 'All categories' %}
        </a>
        {% for category in categories %}
        <a href="?category={{ category.id }}" class="list-group-item list-group-item-action {% if request.GET.category == category.id|stringformat:'s' %}active{% endif %}">
          {% if category.marker_icon.name %}
          <img alt="" src="{{ category.marker_icon.url }}"/>
          {% endif %}
          {{ category.name }}
        </a>
        {% endfor %}
      </div>
    </div>
    <div class="col-md-12">
      {% include '_pagination.html' %}
    </div>
  </div>
{% endblock content %}

willay/templates/claims/export.html
{% extends 'base.html' %}
{% load i18n static form_tags %}
{% block content %}
  <div class="row">
    <div class="col-md-12">
      <form method="post">
        {% csrf_token %}
        <div class="row">
          <div class="col-md-6">
            {% field form.category %}
            {% field form.start_date %}
            {% field form.end_date %}
          </div>
        </div>
        <br/>
        <button class="btn btn-outline-primary" type="submit">
          <i class="fas fa-table"></i>
          {% trans 'Export' %}
        </button>
      </form>
    </div>
  </div>
{% endblock content %}

willay/templates/claims/map.html
{% extends 'base.html' %}
{% load i18n static %}
{% block css %}
  <link href="{% static 'vendor/leaflet/leaflet.css' %}" rel="stylesheet"/>
  <link href="{% static 'vendor/css/leaflet-markercluster.css' %}" rel="stylesheet"/>
  <link href="{% static 'vendor/css/leaflet-markercluster-default.css' %}" rel="stylesheet"/>
  <style>
    #map {
      width: 100%;
      height: 600px;
    }
  </style>
{% endblock css %}
{% block content %}
  <div class="row">
    <div class="col-md-12">
      <div class="float-right">
        <a class="btn btn-outline-success" href="{% url 'claims:claim-create' %}">
          <i class="fas fa-plus"></i>
          {% trans 'New claim' %}
        </a>
        <br/>
        <br/>
      </div>
      <div id="map"></div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">

    </div>
  </div>
{% endblock content %}
{% block javascript %}
  <script src="{% static 'vendor/leaflet/leaflet.js' %}"></script>
  <script src="{% static 'vendor/js/leaflet-markercluster.js' %}"></script>
  <script src="{% static 'js/claims-map.js' %}"></script>
{% endblock javascript %}